### ISSUE TITLE
Change master to main in rule set patterns for OSS repo banners

### ISSUE THREAD

**Issue by jpvajda** [newrelic/.github#31]
We seem to be pointing our url patterns to `master` on the oss site, where the image files are actually the [older ones on master. ](https://github.com/newrelic/opensource-website/blob/master/docs/Open-Source-Category-Snippets.md) simply changing the pattern to look at [main](https://github.com/newrelic/opensource-website/blob/main/docs/Open-Source-Category-Snippets.md) might be a good idea.

```
readme-starts-with-community-header:
    level: error
    rule:
      type: file-starts-with
      options:
        globsAll:
        - README*
        nocase: true
        lineCount: 5
        patterns:
        - https:\/\/github\.com\/newrelic\/opensource-website\/raw\/master\/src\/images\/categories\/Community_Project\.png
        - https:\/\/opensource\.newrelic\.com\/oss-category\/#community-project
        human-readable-pattern: Open source Community header (see https://opensource.newrelic.com/oss-category)
        flags: i
        succeed-on-non-existent: false
    fix:
      type: file-modify
      options:
        text: "[![Community header](https://github.com/newrelic/opensource-website/raw/master/src/images/categories/Community_Project.png)](https://opensource.newrelic.com/oss-category/#community-project)"
        write_mode: prepend
        newlines:
          end: 2
```
